### ISSUE TITLE
如何更改设置LOGO的大小

### ISSUE THREAD

**Issue by li568265102** [IcedWatermelonJuice/HMOSHomePage#2]
在kiwi用，导入LOGO图片后显示很小，想改大一下点怎么改？
![Screenshot_2021-08-21-10-28-21-414_com kiwibrowser browser](https://user-images.githubusercontent.com/77524676/130307783-bc84d9d2-5a8a-4f12-99ad-733428379ea0.jpg)

**Comment by li568265102** [comment]
我用的是GIF动态logo，我尝试过更改logo动图的尺寸，但是并没有什么用处

**Comment by IcedWatermelonJuice** [comment]
你图片发我邮箱（gem_xl@petalmail.com）下，我看一下问题原因。

**Comment by IcedWatermelonJuice** [comment]
我设置的LOGO是将图片自动放缩，直到图片高度达到LOGO最大高度。

**Comment by IcedWatermelonJuice** [comment]
OK了，加上了个高度设置功能。测试了下，应该没什么bug 了。用1.12版本就行

**Comment by li568265102** [comment]
可以调整了，非常感谢
